In [2]:
import numpy as np

In [17]:
a=np.array(list(range(10,20)))

In [18]:
type(a)

numpy.ndarray

In [19]:
a[0]

10

In [20]:
a[0]=50

In [21]:
a

array([50, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
len(a)

10

In [23]:
a.reshape(2,5)

array([[50, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
b=a.reshape(5,2)
a[1]=100
print(b)
# C main ek hi array bnha hu hai

[[ 50 100]
 [ 12  13]
 [ 14  15]
 [ 16  17]
 [ 18  19]]


In [25]:
a.shape


(10,)

In [26]:
b.shape

(5, 2)

In [27]:
a.size

10

In [28]:
b.size

10

In [29]:
np.array([[1,3],[4,8]])

array([[1, 3],
       [4, 8]])

In [34]:
c=np.array([[1,3],[4,8,10]])

In [31]:
a.dtype

dtype('int32')

In [32]:
b.dtype

dtype('int32')

In [35]:
c.dtype

dtype('O')

In [36]:
a.ndim

1

In [37]:
b.ndim

2

In [38]:
c.ndim

1

In [39]:
c.shape

(2,)

In [40]:
c=np.array([[1,3],[4,8]],dtype='float64')

In [41]:
c

array([[1., 3.],
       [4., 8.]])

In [42]:
c.dtype

dtype('float64')

In [44]:
e=np.arange(15)

In [45]:
d=e.copy()

In [46]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [49]:
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [61]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [62]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [63]:
first=np.arange(100).reshape(10,10)

In [65]:
second=np.arange(100).reshape(10,10)

In [66]:
first+second

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [68]:
first-1#New Array is created new object

array([[-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64, 65, 66, 67, 68],
       [69, 70, 71, 72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [69]:
first-np.arange(10)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [71]:
first

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
first

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
first[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
first[0:5,0:5]#python is createing new object but slicing the same array

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [78]:
first[:5,:2]=100

In [79]:
first

array([[100, 100,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 100,  12,  13,  14,  15,  16,  17,  18,  19],
       [100, 100,  22,  23,  24,  25,  26,  27,  28,  29],
       [100, 100,  32,  33,  34,  35,  36,  37,  38,  39],
       [100, 100,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [3]:
matrix=np.random.randint(60,100,5)

In [4]:
matrix

array([74, 72, 67, 71, 67])

In [8]:
l=[1,2,3,4,5,6,7,8,9]
a=np.array(l).reshape(3,3)

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
a@a

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
f=np.arange(20).reshape(5,4)

In [18]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
f.sum()

190

In [20]:
f.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [45]:
norm=np.random.randn(50,40)

In [46]:
norm

array([[ 0.23247817,  0.91627359, -2.10016952, ...,  0.13002349,
         2.94369741, -0.62551004],
       [-0.57820759,  0.1319801 ,  1.31141996, ..., -1.04620346,
         0.29948668,  1.71106648],
       [ 2.78123068, -0.17902959,  0.06947093, ..., -0.13752247,
         0.2969169 ,  0.83817155],
       ...,
       [ 0.9721788 ,  0.40446508, -0.26572524, ..., -0.10769541,
         0.78917785, -1.45126041],
       [-0.85325828, -0.60899335,  0.3552933 , ...,  0.03093736,
        -0.38317149,  1.3943858 ],
       [ 0.83461698, -0.83371122,  0.41490054, ..., -1.01588392,
         1.36430253, -0.6243706 ]])

In [47]:
norm.mean()#python doesnt provide mean with axis but numpy do

0.038772779422946886

In [48]:
np.std(norm)

1.011733323550048

In [49]:
sum(f)

array([40, 45, 50, 55])

In [56]:
f+5#numpy operation not python operation

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [59]:
(np.random.rand(5,5)*100).astype(int)

array([[11, 19, 86, 53,  2],
       [17, 42, 58,  4, 97],
       [27, 22, 76, 94, 13],
       [30, 52, 66, 97, 95],
       [58, 68, 43, 84, 95]])

In [60]:
np.random.rand(1)

array([0.32389334])

In [62]:
np.random.randint(0,100,(5,5))

array([[ 8, 49, 98, 11,  2],
       [92, 44,  3, 22, 78],
       [89, 54, 43, 11,  6],
       [58, 44, 12, 25, 95],
       [23, 69,  8, 70, 69]])

In [65]:
np.random.random((4,6))

array([[0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668,
        0.59505206],
       [0.52981736, 0.41880743, 0.33540785, 0.62251943, 0.43814143,
        0.73588211],
       [0.51803641, 0.5788586 , 0.6453551 , 0.99022427, 0.8198582 ,
        0.41320093],
       [0.87626766, 0.82375943, 0.05447451, 0.71863724, 0.80217056,
        0.73640664]])

In [81]:
np.random.seed(6)

In [86]:
np.random.random((4,6))

array([[0.86303041, 0.55846662, 0.54670783, 0.36782466, 0.82815669,
        0.27635046],
       [0.12565834, 0.56278108, 0.26733901, 0.77503493, 0.17940635,
        0.78325667],
       [0.60799632, 0.04174888, 0.56127513, 0.66813773, 0.93839261,
        0.78600586],
       [0.75043047, 0.49705098, 0.0427325 , 0.8168675 , 0.01362374,
        0.55004119]])

In [88]:
np.power(f,4)

array([[     0,      1,     16,     81],
       [   256,    625,   1296,   2401],
       [  4096,   6561,  10000,  14641],
       [ 20736,  28561,  38416,  50625],
       [ 65536,  83521, 104976, 130321]], dtype=int32)

In [89]:
np.sum(f,axis=0,keepdims=True)

array([[40, 45, 50, 55]])

In [90]:
np.sum(f,axis=1,keepdims=True)

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [92]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [93]:
s=np.arange(20).reshape((4,5))

In [94]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
np.dot(f,s)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462],
       [430, 484, 538, 592, 646],
       [550, 620, 690, 760, 830]])

In [98]:
t=np.dot(s,f)

In [99]:
t

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]])

In [100]:
np.hstack([f,f])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])

In [101]:
np.vstack((f,f))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [102]:
np.concatenate((f,f),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [103]:
np.concatenate((f,f),axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])

In [50]:
f3d=np.arange(27).reshape(3,3,3)

In [51]:
f3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
f3d.sum(axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

In [53]:
f3d.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [54]:
f3d.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [55]:
np.median(f,axis=0)

array([ 8.,  9., 10., 11.])